### ISSUE TITLE
Error message not clear when certificate chain is not correct 

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#12]
When certificate chain is not correct error message could be more clear.

**Comment by Tjeerd** [comment]
Could you please provide a Metadata URL for which this error is displayed?

**Comment by teunfransen** [comment]
https://imogen.zoetekouw.net/testsp/module.php/saml/sp/metadata.php/default-sp

**Comment by teunfransen** [comment]
same as #21
