### ISSUE TITLE
Add FriendlyName to RequestedAttribute

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#13]

**Comment by Tjeerd** [comment]
@teunfransen: Please elaborate a bit about what is meant with a 'FriendlyName'.

**Comment by teunfransen** [comment]
<md:RequestedAttribute Name="urn:oid:0.9.2342.19200300.100.1.3" isRequired="true"/>

It would be nice if, besides the NAME also FriendlyName is available:

<saml:Attribute FriendlyName="telephoneNumber" Name="urn:oid:2.5.4.20"
