### ISSUE TITLE
Add buttons to change form status

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#24]
Add a button on the backend that allows changing the status of the form. Forms that are in draft can be changed to finished, and finished forms can be changed to draft status.

**Comment by Tjeerd** [comment]
Do you expect the 'a subscription has been finished' mail to be sent as well when an admin 'finishes' a subscription?

**Comment by teunfransen** [comment]
No, it's not necessary to send an email when the admin finishes a form.
