### ISSUE TITLE
Exported metadata is not accepted by Service Registry (JANUS)

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#25]
For Janus it is not possible to read the metadata file below. This is an exception. Most exported metadatafiles do work. Please investigate what the problem is.

https://support.surfconext.nl/intake/subscription/6470058c-c6ab-11e4-98aa-005056912be7/metadata

**Comment by Tjeerd** [comment]
Error is (after testing the URL with our own Form ;):
```
Error 1871: Element '{urn:oasis:names:tc:SAML:2.0:metadata}Extensions': This element is not expected. Expected is ( {urn:oasis:names:tc:SAML:2.0:metadata}AttributeConsumingService ).
```

**Comment by Tjeerd** [comment]
So our own Metadata generator is generating invalid XML in some cases.
