### ISSUE TITLE
Metadata url not accepted in form (message not specific enough)

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#26]
message: De metadata XML is niet valide gezien de gerelateerde XSD
Is it possible to make the error message more specific?

https://tas.fhict.nl/identity/saml2/metadata

**Comment by teunfransen** [comment]
The same goes for https://nyenrode.crosscampus.nl/data/hnp/saml/nyenrode/metadata.xml

**Comment by Tjeerd** [comment]
Errors for `https://tas.fhict.nl/identity/saml2/metadata` are:
```
Error 1868: Element '{urn:oasis:names:tc:SAML:2.0:metadata}OrganizationName': The attribute '{http://www.w3.org/XML/1998/namespace}lang' is required but missing.
Error 1868: Element '{urn:oasis:names:tc:SAML:2.0:metadata}OrganizationDisplayName': The attribute '{http://www.w3.org/XML/1998/namespace}lang' is required but missing.
Error 1868: Element '{urn:oasis:names:tc:SAML:2.0:metadata}OrganizationURL': The attribute '{http://www.w3.org/XML/1998/namespace}lang' is required but missing.
```

The URL `https://nyenrode.crosscampus.nl/data/hnp/saml/nyenrode/metadata.xml` doesn't trigger any errors as far as I can see.

**Comment by teunfransen** [comment]
De metadata kon niet worden ingelezen:
In regel 31 <OrganizationName>Stichting Fontys</OrganizationName> trad de voldende fout op:
"The attribute '{http://www.w3.org/XML/1998/namespace}lang' is required but missing" 
Los dit probleem op en probeer het opnieuw. Bij vragen neem contact op met support@surfconext.

**Comment by Tjeerd** [comment]
A new translations key has been added: `Invalid metadata: %errors%` for these error messages. Please check if this is sufficient.
