### ISSUE TITLE
Search functionality to search subscriptions

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#27]
Please add the functionality to search subscriptions.

**Comment by teunfransen** [comment]
The search option is not available. Is there something that should be tweaked at the server? 
![screen shot 2015-03-25 at 08 45 32](https://cloud.githubusercontent.com/assets/10402311/6820053/55f555c6-d2cb-11e4-9045-d99d005dde28.png)

**Comment by Tjeerd** [comment]
I have no idea how this is possible, please try to deploy a new release, refresh the page (ctrl+f5) and check the log files in <root>/app/logs/prod.log.

**Comment by baszoetekouw** [comment]
I've deployed a new release, made sure my caches were cleared, but still no search functionality :(
There's nothing in the logs, unfortunately.

Could it have something to do with our ancient php version?  The grid layout builder seems to be buried quite deep in the stack...

**Comment by Tjeerd** [comment]
No, I don't think so, I'm developing on CentOS/PHP 5.3.3 to be sure as well.

**Comment by Tjeerd** [comment]
Caused by a caching issue, fixed by moving cache (back) to filesystem.
