### ISSUE TITLE
Metadata url (standard ADFS) not accepted

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#31]
Although this metadata file is correct (opening the file in browser) the form does not accept the url.

Could you investigate the problem and fix it?

https://sso.2at.net/federationmetadata/2007-06/federationmetadata.xml

**Comment by Tjeerd** [comment]
Errors are:
```
Error 1876: Element '{urn:oasis:names:tc:SAML:2.0:metadata}RoleDescriptor': The type definition is abstract.
Error 1851: Element '{urn:oasis:names:tc:SAML:2.0:metadata}RoleDescriptor', attribute '{http://www.w3.org/2001/XMLSchema-instance}type': The QName value '{http://docs.oasis-open.org/wsfed/federation/200706}ApplicationServiceType' of the xsi:type attribute does not resolve to a type definition.
```

**Comment by baszoetekouw** [comment]
This metadata correctly validates with xmllint if you import the wsfed xsd from http://docs.oasis-open.org/wsfed/federation/200706

**Comment by baszoetekouw** [comment]
The make this more explicit:  Next to the normal SAML2.0 xsds, I have added the following xsds to my xmllint catalog:
* http://docs.oasis-open.org/wsfed/federation/v1.2/os/ws-federation.xsd
* http://docs.oasis-open.org/wsfed/authorization/v1.2/os/ws-authorization.xsd
* http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd

and I'm running xmllint like this:
```
xmllint -noout -schema ${XMLDIR}/saml-schema-metadata-2.0.xsd -schema ${XMLDIR}/ws-federation.xsd "$METADATAFILE"
```

This correctly validates both normal SAML metadata (like from https://engine.surfconext.nl/authentication/idp/metadata) and the ADFS metadata referenced above.

**Comment by Tjeerd** [comment]
Right, because the reference to the mentioned xsd files is not available in the source XML (or XSD) we have to find a way to manually add this reference to the source document just before validating the document.

**Comment by baszoetekouw** [comment]
I'm not sure if I understand your question exactly, but wouldn't it suffice to validate against the following dtd instead of the saml2 one?:

```xml
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/notused">
	<xs:import namespace="urn:oasis:names:tc:SAML:2.0:metadata" schemaLocation="http://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd" />
	<xs:import namespace="http://docs.oasis-open.org/wsfed/federation/200706" schemaLocation="http://docs.oasis-open.org/wsfed/federation/v1.2/os/ws-federation.xsd" />
</xs:schema>
```

**Comment by Tjeerd** [comment]
Thanks for the hint! I learned something new today ;).
