### ISSUE TITLE
Is the MailReport cron running?

### ISSUE THREAD

**Issue by Tjeerd** [SURFnet/Service-provider-registration#35]
Every once in a while a mail report should be send to `support@surfconext.nl`. This can be done by calling `php app/console app:mail:report`, preferably by using a cron script.

Has this script been enabled in the cron and are reports being sent?

**Comment by teunfransen** [comment]
Bas will look into this.

**Comment by baszoetekouw** [comment]
Hmm, running that gives the following error:
```
[bas@info2]/www/support/spform/current> cd /www/support/spform/current && php ./app/console app:mail:report
PHP Fatal error:  Class 'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle' not found in /www/support/spform/releases/20150323083914/app/AppKernel.php on line 40
```

**Comment by baszoetekouw** [comment]
How often should it be run, btw?

**Comment by teunfransen** [comment]
I guess once a week should be fine for now.

**Comment by baszoetekouw** [comment]
It seems the SensioGeneratorBundle is missing from the composer;  @Tjeerd could you take a look at that?

**Comment by Tjeerd** [comment]
Ah, right, I'm sorry the command should be:

    php app/console app:mail:report --env=prod

The `env` param determines the environment the script is run in. By default this is `dev` which requires the `SensioGeneratorBundle`, this bundle is not installed though because the install/deploy script is run with the `env` param set to `prod`.

**Comment by baszoetekouw** [comment]
Indeed, works fine now.  
Cronjob is set to run weekly on early monday mornings
