### ISSUE TITLE
Form seems to cache metadata URL

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#38]
It looks like the form caches metadata URLs (or the data extracted from the metadata).

We found a case were a client had updated the saml certificate from 1024 bits to 2048 bits. When the updated metadata file was put in the form, it showed the old 1024 certificate.

https://eur-acceptation.comradsdev.com/simplesaml/module.php/saml/sp/metadata.php/default-sp

**Comment by Tjeerd** [comment]
Yes, the metadata is cached to prevent the form from retrieving the metadata on every single validation and save (ajax) call. If no caching would be applied the form and validation of the form will be much slower.

It is cached for 24 hours, we can lower this cache time to, for example, 1 hour, so changes will be visible sooner. Is this acceptable or should it be even lower?

**Comment by teunfransen** [comment]
So assume that the caching is deactivated, every time a metadata url is provided takes as long as it takes now to validate the url? Because I think that the validation is very quickly.

**Comment by Tjeerd** [comment]
Caching of metadata has temporarily been disabled to check the effect on performance.

**Comment by teunfransen** [comment]
works perfectly. Application respons is ok.
