### ISSUE TITLE
Logo requirement enhancement

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#43]
Change in policy. Logos have the following requirements:

Max dimensions: 500x300 px
Max size: 1 MB

Rest of the requirements (PNG or GIF, Losless etc.) are unchanged.

**Comment by Tjeerd** [comment]
I've found a some spare time ;) Fixed in #23809b2 and made available on release branch.

**Comment by teunfransen** [comment]
Nice
