### ISSUE TITLE
Mention name of SP in subject of mail when form has been submitted

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#44]
Please add the name of the SP in the subject of the email that is send to support@surfconext.nl.

English:
(CXT-number) <name sp> finished SP registration form
Dutch:
(CXT-number) <name sp> heeft SP registratieformulier afgerond

**Comment by Tjeerd** [comment]
I am not sure which fields you mean with the "name of the SP" or the "CXT-number". Are this existing fields in the form or should they be added?

**Comment by teunfransen** [comment]
By name of the SP I mean the 'name' field in the form. Can this be reused in the mail subject? 
'CXT-number' is already in the subject of this mail (see image below). 

So the mail subject should look like this (changed it a bit):

English:
CXT-number SP <name> finished registration form
Dutch:
(CXT-number) SP <name> heeft het registratieformulier afgerond


![screen shot 2015-05-07 at 08 45 47](https://cloud.githubusercontent.com/assets/10402311/7509792/843350d2-f495-11e4-9624-7db321d0ce44.png)

**Comment by Tjeerd** [comment]
You can now use '%nameEn%' and/or '%nameNl%' in the "mail.notification.subject" translation string.

**Comment by teunfransen** [comment]
Works perfectly!
