### ISSUE TITLE
Number of generated metadata urls fail when imported in Janus

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#45]
A number of metadata urls generated by the form is not accepted by the metadata converter (XML to SAML) of simpleSAML (in Janus). 

See example below:

De file
https://support.surfconext.nl/intake/subscription/aee1de68-d783-11e4-98aa-005056912be7/metadata
geeft de volgende error:
----
[root@beta log]# grep  69154d0d95 messages
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95]
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] Backtrace:
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 1
/data/simplesamlphp/simplesamlphp-1.13.2/www/_include.php:37
(SimpleSAML_exception_handler)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 0 [builtin] (N/A)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] Caused by:
Exception: Missing ServiceName in AttributeConsumingService.
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] Backtrace:
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 5
/data/simplesamlphp/simplesamlphp-1.13.2/vendor/simplesamlphp/saml2/src/SAML2/XML/md/AttributeConsumingService.php:72
(SAML2_XML_md_AttributeConsumingService::__construct)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 4
/data/simplesamlphp/simplesamlphp-1.13.2/vendor/simplesamlphp/saml2/src/SAML2/XML/md/SPSSODescriptor.php:63
(SAML2_XML_md_SPSSODescriptor::__construct)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 3
/data/simplesamlphp/simplesamlphp-1.13.2/vendor/simplesamlphp/saml2/src/SAML2/XML/md/EntityDescriptor.php:132
(SAML2_XML_md_EntityDescriptor::__construct)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 2
/data/simplesamlphp/simplesamlphp-1.13.2/lib/SimpleSAML/Metadata/SAMLParser.php:301
(SimpleSAML_Metadata_SAMLParser::parseDescriptorsElement)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 1
/data/simplesamlphp/simplesamlphp-1.13.2/lib/SimpleSAML/Metadata/SAMLParser.php:281
(SimpleSAML_Metadata_SAMLParser::parseDescriptorsString)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] 0
/data/simplesamlphp/simplesamlphp-1.13.2/www/admin/metadata-converter.php:11
(N/A)
May  4 15:08:59 beta simplesamlphp[17919]: 3 [69154d0d95] Error report
with id d7d934a3 generated.
[root@beta log]#
----

**Comment by teunfransen** [comment]
Looks like it's better now.

**Comment by teunfransen** [comment]
At this moment the value of ServiceName is static: 'SP'. It would be nice if this value is filled with the value of "name" from de form.
Could you distinguish the Name (en) and Name (nl)?

**Comment by Tjeerd** [comment]
I've updated the code so a <ServiceName> node is added with the value of "Name (en)" when the original metadata does not contain a <ServiceName> node.
