### ISSUE TITLE
Error mail #1

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#47]
Below the first error mail. 

-----------
Hi,

An error occurred when generating/exporting metadata of a SP registration: [1]https://support.surfconext.nl/intake/subscription/d9cd5f3e-f49e-11e4-98aa-005056912be7/metadataError
The metadata XML is invalid considering the associated XSD

At line 4, column 0, code 1871:
Element '
{urn:oasis:names:tc:SAML:2.0:metadata}

KeyDescriptor': Missing child element(s). Expected is (
{http://www.w3.org/2000/09/xmldsig#}

KeyInfo ).

XML
<?xml version="1.0"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="uvagoalsetting-test">
<SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><md:Extensions xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"><ui:UIInfo xmlns:ui="urn:oasis:names:tc:SAML:metadata:ui"><ui:Description xml:lang="en"/><ui:Description xml:lang="nl"/><ui:DisplayName xml:lang="en"/><ui:DisplayName xml:lang="nl"/><ui:InformationURL xml:lang="en"/></ui:UIInfo></md:Extensions>
<KeyDescriptor/>
<NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
<AssertionConsumerService index="1" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://goalsetting.ihatestatistics.com/login/callback"/>
<md:AttributeConsumingService xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" index="0"><md:ServiceName xml:lang="en"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:eduPersonAffiliation" FriendlyName="Affiliation"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:mail" FriendlyName="Email address"/><md:RequestedAttribute Name="urn:mace:terena.org:attribute-def:schacHomeOrganization" FriendlyName="Organization"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:sn" FriendlyName="Surname"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:givenName" FriendlyName="Given name"/></md:AttributeConsumingService></SPSSODescriptor>
<md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="support"><md:GivenName>Vladimer</md:GivenName><md:SurName>Kobayashi</md:SurName><md:EmailAddress>v.kobayashi@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson><md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="technical"><md:GivenName>Alan</md:GivenName><md:SurName>Berg</md:SurName><md:EmailAddress>a.m.berg@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson><md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="administrative"><md:GivenName>Stefan</md:GivenName><md:SurName>Mol</md:SurName><md:EmailAddress>s.t.mol@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson></EntityDescriptor>

Ticket No.CXT-12866ContactRobin Hansma (robin@ihatestatistics.com / 0610834486)Metadata URLhttps://goalsetting.ihatestatistics.com/metadataLogo URLName (en)Description (en)Name (nl)Description (nl)Application URLEula URLAdministrative contactStefan Mol (s.t.mol@uva.nl / )Technical contactAlan Berg (a.m.berg@uva.nl / )Support contactVladimer Kobayashi (v.kobayashi@uva.nl / )Given name attribute1 - urn:oid:2.5.4.3Sur name attribute1 - urn:oid:2.5.4.42Common name attribute-Display name attribute-Email address attribute1 - urn:oid:0.9.2342.19200300.100.1.3Organization attribute1 - urn:oid:1.3.6.1.4.1.25178.1.2.9Organization type attribute-Affiliation attribute1 - urn:oid:1.3.6.1.4.1.5923.1.1.1.1Entitlement attribute-Principle name attribute-Uid attribute-Preferred language attribute-Organizational unit attribute-Personal code attribute-Comments

Kind regards,

SURFconext
----------------------------------------------------------------------------------------
[1] https://support.surfconext.nl/intake/subscription/d9cd5f3e-f49e-11e4-98aa-005056912be7/metadata
[Created via e-mail received from: support@surfconext.nl]

**Comment by Tjeerd** [comment]
Teun, do you have the original error mail? Because this view has removed all the XML.

**Comment by teunfransen** [comment]
Hi,
An error occurred when generating/exporting metadata of a SP registration: https://support.surfconext.nl/intake/subscription/d9cd5f3e-f49e-11e4-98aa-005056912be7/metadata

Error
    The metadata XML is invalid considering the associated XSD

                        At line 4, column 0, code 1871:
            Element '{urn:oasis:names:tc:SAML:2.0:metadata}KeyDescriptor': Missing child element(s). Expected is ( {http://www.w3.org/2000/09/xmldsig#}KeyInfo ).

            
XML
    <?xml version="1.0"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="uvagoalsetting-test">
  <SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><md:Extensions xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"><ui:UIInfo xmlns:ui="urn:oasis:names:tc:SAML:metadata:ui"><ui:Description xml:lang="en"/><ui:Description xml:lang="nl"/><ui:DisplayName xml:lang="en"/><ui:DisplayName xml:lang="nl"/><ui:InformationURL xml:lang="en"/></ui:UIInfo></md:Extensions>
    <KeyDescriptor/>
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <AssertionConsumerService index="1" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://goalsetting.ihatestatistics.com/login/callback"/>
  <md:AttributeConsumingService xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" index="0"><md:ServiceName xml:lang="en"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:eduPersonAffiliation" FriendlyName="Affiliation"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:mail" FriendlyName="Email address"/><md:RequestedAttribute Name="urn:mace:terena.org:attribute-def:schacHomeOrganization" FriendlyName="Organization"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:sn" FriendlyName="Surname"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:givenName" FriendlyName="Given name"/></md:AttributeConsumingService></SPSSODescriptor>
<md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="support"><md:GivenName>Vladimer</md:GivenName><md:SurName>Kobayashi</md:SurName><md:EmailAddress>v.kobayashi@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson><md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="technical"><md:GivenName>Alan</md:GivenName><md:SurName>Berg</md:SurName><md:EmailAddress>a.m.berg@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson><md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="administrative"><md:GivenName>Stefan</md:GivenName><md:SurName>Mol</md:SurName><md:EmailAddress>s.t.mol@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson></EntityDescriptor>

Ticket No.
CXT-12866
Contact
Robin Hansma (robin@ihatestatistics.com / 0610834486)
Metadata URL
https://goalsetting.ihatestatistics.com/metadata
Logo URL
Name (en)
Description (en)
Name (nl)
Description (nl)
Application URL
Eula URL
Administrative contact
Stefan Mol (s.t.mol@uva.nl / )
Technical contact
Alan Berg (a.m.berg@uva.nl / )
Support contact
Vladimer Kobayashi (v.kobayashi@uva.nl / )
Given name attribute
1 - urn:oid:2.5.4.3
Sur name attribute
1 - urn:oid:2.5.4.42
Common name attribute
-
Display name attribute
-
Email address attribute
1 - urn:oid:0.9.2342.19200300.100.1.3
Organization attribute
1 - urn:oid:1.3.6.1.4.1.25178.1.2.9
Organization type attribute
-
Affiliation attribute
1 - urn:oid:1.3.6.1.4.1.5923.1.1.1.1
Entitlement attribute
-
Principle name attribute
-
Uid attribute
-
Preferred language attribute
-
Organizational unit attribute
-
Personal code attribute
-
Comments
Kind regards,

SURFconext

_______________________________________________
Surfconext-support mailing list
Surfconext-support@surfnet.nl
https://lijst.surfnet.nl/mailman/listinfo/surfconext-support

**Comment by teunfransen** [comment]
I'll forward the mail to your personal email.

**Comment by Tjeerd** [comment]
Ok thanks! You can also use MD syntax here, enclose the code with ```, see: https://guides.github.com/features/mastering-markdown/

**Comment by Tjeerd** [comment]
Back to the original issue: it is kind of strange, because the original metadata is not valid at all. If I use the metadata url (https://goalsetting.ihatestatistics.com/metadata) in a new form, it cannot be submitted.

So how is this possible? Could you ask the contact person what he did exactly to be able to save the form? Another possibility is that someone finished the form manually in the backend and tried to access the generated metadata after that?

**Comment by teunfransen** [comment]
Yes it's very strange. As far as I know nobody finished the form from the backend. I will test this by finishing a newly made form with the metadata from 'ithatestatistics'.

The problem stays that we keep receiving the same error email (at 15:00 we reveived the 15th email).

**Comment by teunfransen** [comment]
Yes, so when I press export on the newly made form (that I closed myself) with the metadata of 'ihatestatistics' a error mail is sent to support@surfconext.nl.
I however find it hard to believe that we pressed the exportbutton 15 times the last two days....

**Comment by Tjeerd** [comment]
I followed the link, from the error mail, a couple of times as well, since it is public, you can never really know who is accessing the link (maybe Google Mail follows links in mails as well, for example).

**Comment by teunfransen** [comment]
Ai! Big Brother is watching us! :-). Ok, I guess this case was an exception. Normally this form couldn't have been finished. If this happens again a deeper investigation is necessary. For now I close this issue.
