### ISSUE TITLE
Error mail #1 seems to be sent twice

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#48]
It looks like the error mail is sent twice. Could you check whether or not this is the case?

-----------------
Hi,

An error occurred when generating/exporting metadata of a SP registration: [1]https://support.surfconext.nl/intake/subscription/d9cd5f3e-f49e-11e4-98aa-005056912be7/metadataError
The metadata XML is invalid considering the associated XSD

At line 4, column 0, code 1871:
Element '
{urn:oasis:names:tc:SAML:2.0:metadata}

KeyDescriptor': Missing child element(s). Expected is (
{http://www.w3.org/2000/09/xmldsig#}

KeyInfo ).

XML
<?xml version="1.0"?>
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="uvagoalsetting-test">
<SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><md:Extensions xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"><ui:UIInfo xmlns:ui="urn:oasis:names:tc:SAML:metadata:ui"><ui:Description xml:lang="en"/><ui:Description xml:lang="nl"/><ui:DisplayName xml:lang="en"/><ui:DisplayName xml:lang="nl"/><ui:InformationURL xml:lang="en"/></ui:UIInfo></md:Extensions>
<KeyDescriptor/>
<NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
<AssertionConsumerService index="1" isDefault="true" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://goalsetting.ihatestatistics.com/login/callback"/>
<md:AttributeConsumingService xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" index="0"><md:ServiceName xml:lang="en"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:eduPersonAffiliation" FriendlyName="Affiliation"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:mail" FriendlyName="Email address"/><md:RequestedAttribute Name="urn:mace:terena.org:attribute-def:schacHomeOrganization" FriendlyName="Organization"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:sn" FriendlyName="Surname"/><md:RequestedAttribute Name="urn:mace:dir:attribute-def:givenName" FriendlyName="Given name"/></md:AttributeConsumingService></SPSSODescriptor>
<md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="support"><md:GivenName>Vladimer</md:GivenName><md:SurName>Kobayashi</md:SurName><md:EmailAddress>v.kobayashi@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson><md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="technical"><md:GivenName>Alan</md:GivenName><md:SurName>Berg</md:SurName><md:EmailAddress>a.m.berg@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson><md:ContactPerson xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" contactType="administrative"><md:GivenName>Stefan</md:GivenName><md:SurName>Mol</md:SurName><md:EmailAddress>s.t.mol@uva.nl</md:EmailAddress><md:TelephoneNumber/></md:ContactPerson></EntityDescriptor>

Ticket No.CXT-12866ContactRobin Hansma (robin@ihatestatistics.com / 0610834486)Metadata URLhttps://goalsetting.ihatestatistics.com/metadataLogo URLName (en)Description (en)Name (nl)Description (nl)Application URLEula URLAdministrative contactStefan Mol (s.t.mol@uva.nl / )Technical contactAlan Berg (a.m.berg@uva.nl / )Support contactVladimer Kobayashi (v.kobayashi@uva.nl / )Given name attribute1 - urn:oid:2.5.4.3Sur name attribute1 - urn:oid:2.5.4.42Common name attribute-Display name attribute-Email address attribute1 - urn:oid:0.9.2342.19200300.100.1.3Organization attribute1 - urn:oid:1.3.6.1.4.1.25178.1.2.9Organization type attribute-Affiliation attribute1 - urn:oid:1.3.6.1.4.1.5923.1.1.1.1Entitlement attribute-Principle name attribute-Uid attribute-Preferred language attribute-Organizational unit attribute-Personal code attribute-Comments

Kind regards,

SURFconext
----------------------------------------------------------------------------------------
[1] https://support.surfconext.nl/intake/subscription/d9cd5f3e-f49e-11e4-98aa-005056912be7/metadata
[Created via e-mail received from: support@surfconext.nl]

**Comment by Tjeerd** [comment]
Everytime the 'export' link is clicked in the backend or from the mail, the error mail is send. Quick solution would be to set the form back to 'draft' so the the export link is not visible anymore (it can still be accessed though).

Ofcourse we can always disable sending the mails and find another mechanism to report the errors. Maybe a log file which is checked once a week?
