### ISSUE TITLE
Invitation mail is often received in spambox

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#49]
We sometimes get the message that the invitation mail for the SP registration form is received in the spambox. Could you please look into this?

**Comment by Tjeerd** [comment]
I'm not sure if anything can be done about this from the application's point of view.

It might be more easy to add the sender to an 'allowed' list, or explicitly mark the mails as "not spam" so they won't get marked in the future.

**Comment by surfnet-niels** [comment]
I would not know how the receiver of the invite could (ever) do that, as he/she would not know who the sender is. Also spam filters are generally not under end user control.

Typically a few things must be in place:
* Not too much crap in the message. I would think this is ok here
* DNS of the sender email adress must be correct, both forward and reverse, both v4 and v6 
that might be something worth checking.

**Comment by Tjeerd** [comment]
Ah, I'm sorry, I assumed this was about the mails sent to 'support@surf...'.

**Comment by teunfransen** [comment]
I believe some configurations have been changed at our side.
