### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#50]
An evaluation of the form shows that there is some confusion about some fields and what has to be filled in:
-Greyed out fields on the metadata page: a placeholder with the text 'Information is automatically subtracted from the Metadata URL'.
-Attributes page: for some people it's unclear what has to be filled in here. I guess it would help when the field becomes active (box is checked) the placeholder appears: 'for what purpose this attribute is used by the service?' or 'The service will use this attribute to....'.

**Comment by relaxnow** [comment]
![screen shot 2015-11-02 at 12 24 23](https://cloud.githubusercontent.com/assets/524386/10880596/aec6a278-815c-11e5-95ab-ee876aed7ffd.png)
![screen shot 2015-11-02 at 12 23 41](https://cloud.githubusercontent.com/assets/524386/10880597/aec8a712-815c-11e5-9415-dc5128658707.png)

Done.
