### ISSUE TITLE
Remove asterix at attributes page

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#52]
Due to the fact that all attributes have an asterix, some users think they have to check all. And frankly, they are not all required. The flow: 'when you check a box, it's you're required to fill the field' is not clear.

**Comment by relaxnow** [comment]
![screen shot 2015-11-02 at 12 23 41](https://cloud.githubusercontent.com/assets/524386/10880585/92eec8a0-815c-11e5-94f6-7eab779ba1c1.png)

Asterixes have been removed.
