### ISSUE TITLE
Export format form

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#7]
When the form is submitted, the form should generate a file which integrates input from the form into the file. This file should be easily imported in JANUS (probably XML. Ask Boy or Lucas for the best option)

**Comment by Tjeerd** [comment]
I've added the possibilty to 'export' a subscription. The can be done using the new 'export' link in the admin for completed subscriptions. This will open a new window where the generated metadata xml will be shown. It uses the original metadata as input but with updated values which were supplied in the form. The link to the export has also been added to the notification mail.
