### ISSUE TITLE
Form sends mail from address support@surfconext.nl

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#9]
This generates an auto-reply mail which is contaminating. Is it possible to change the outgoing address?

**Comment by Tjeerd** [comment]
Yes, the "sender" address can be adjusted in the config: app/config/parameters.yml, key 'mail_from'. This should be adjusted by the 'maintainer', Bas in this case.

After changing the parameter the cache should be cleared: `php app/console ca:cl -e prod`
